"""add_exchange_rates_table

Revision ID: 65d1742033a2
Revises: 
Create Date: 2026-07-17 22:30:03.663051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d1742033a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.create_table(
        'exchange_rates',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('currency_code', sa.String(length=10), nullable=False),
        sa.Column('rate_to_usd', sa.Float(), nullable=False),
        sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_exchange_rates_currency_code'), 'exchange_rates', ['currency_code'], unique=True)
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_currency_code'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
