"""add_exchange_rates_table

Revision ID: 65d1742033a2
Revises: 
Create Date: 2026-07-17 22:30:03.663051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d1742033a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_rate', sa.Column('currency_code', sa.String(length=3), nullable=False))
    op.add_column('exchange_rate', sa.Column('rate_to_usd', sa.Float(), nullable=True))
    op.add_column('exchange_rate', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_exchange_rate_currency_code'), 'exchange_rate', ['currency_code'], unique=True)
    op.create_index(op.f('ix_exchange_rate_id'), 'exchange_rate', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_rate_id'), table_name='exchange_rate')
    op.drop_index(op.f('ix_exchange_rate_currency_code'), table_name='exchange_rate')
    op.drop_column('exchange_rate', 'update_at')
    op.drop_column('exchange_rate', 'rate_to_usd')
    op.drop_column('exchange_rate', 'currency_code')
    # ### end Alembic commands ###
